// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBINAijB-vzLCC4imxqmDgGIogcNQRkbyA',
    appId: '1:760414861460:web:551d1ea98c94a185f11c81',
    messagingSenderId: '760414861460',
    projectId: 'techie-talk',
    authDomain: 'techie-talk.firebaseapp.com',
    storageBucket: 'techie-talk.firebasestorage.app',
    measurementId: 'G-BQR7PZSCWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC17tNJ4eRNM-YuM-i4QjO0tSO78U6vc9Q',
    appId: '1:760414861460:android:61b5fcf0a860d126f11c81',
    messagingSenderId: '760414861460',
    projectId: 'techie-talk',
    storageBucket: 'techie-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3iIi67Z_mWJnsgBOoE5NUOoYcQihrOJE',
    appId: '1:760414861460:ios:12f555c78e0a122bf11c81',
    messagingSenderId: '760414861460',
    projectId: 'techie-talk',
    storageBucket: 'techie-talk.firebasestorage.app',
    iosBundleId: 'com.example.techieTalk',
  );
}
